In [172]:
import pandas as pd
import numpy as np

In [173]:
from numpy.random import randn
np.random.seed(101)

rand_mat = randn(5,4)

In [174]:
rand_mat

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651],
       [ 0.19079432,  1.97875732,  2.60596728,  0.68350889]])

In [175]:
df = pd.DataFrame(data=rand_mat)
df

          0         1         2         3
0  2.706850  0.628133  0.907969  0.503826
1  0.651118 -0.319318 -0.848077  0.605965
2 -2.018168  0.740122  0.528813 -0.589001
3  0.188695 -0.758872 -0.933237  0.955057
4  0.190794  1.978757  2.605967  0.683509

In [176]:
df = pd.DataFrame(data=rand_mat, index=['A', 'B', 'C', 'D', 'E'])

In [177]:
df

          0         1         2         3
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [178]:
df = pd.DataFrame(data=rand_mat, index='A B C D E'.split()).round(2)
df

      0     1     2     3
A  2.71  0.63  0.91  0.50
B  0.65 -0.32 -0.85  0.61
C -2.02  0.74  0.53 -0.59
D  0.19 -0.76 -0.93  0.96
E  0.19  1.98  2.61  0.68

In [179]:
df.columns = 'W X Y Z'.split()

In [180]:
df['New'] = (df['W'] + df['Y']).round(2)
df['New']

A    3.62
B   -0.20
C   -1.49
D   -0.74
E    2.80
Name: New, dtype: float64

In [181]:
df.drop('New', axis=1, inplace=True)

In [182]:
df

      W     X     Y     Z
A  2.71  0.63  0.91  0.50
B  0.65 -0.32 -0.85  0.61
C -2.02  0.74  0.53 -0.59
D  0.19 -0.76 -0.93  0.96
E  0.19  1.98  2.61  0.68

In [183]:
df.loc['A'] # retrieve the specific row using the index

W    2.71
X    0.63
Y    0.91
Z    0.50
Name: A, dtype: float64

In [184]:
df.iloc[0]

W    2.71
X    0.63
Y    0.91
Z    0.50
Name: A, dtype: float64

In [185]:
df.iloc[[0, 3]]  # Selects rows by integer position (0-based indexing). 
                  # Retrieves the first row (index 0) and the fourth row (index 3) of the DataFrame.

      W     X     Y     Z
A  2.71  0.63  0.91  0.50
D  0.19 -0.76 -0.93  0.96

In [186]:
df.loc[['A', 'E']]  # Selects rows by label using the DataFrame’s index.
                     # Retrieves the rows with index names 'A' and 'E'.

      W     X     Y     Z
A  2.71  0.63  0.91  0.50
E  0.19  1.98  2.61  0.68

In [187]:
df.loc[['A','B'],['Y','Z']] # or df.loc[['A','B']][['Y','Z']]

      Y     Z
A  0.91  0.50
B -0.85  0.61

In [188]:
df.iloc[[0,1]][['W','X']]

      W     X
A  2.71  0.63
B  0.65 -0.32

---

In [189]:
df > 0

       W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [190]:
df[df > 0]

      W     X     Y     Z
A  2.71  0.63  0.91  0.50
B  0.65   NaN   NaN  0.61
C   NaN  0.74  0.53   NaN
D  0.19   NaN   NaN  0.96
E  0.19  1.98  2.61  0.68

In [191]:
df['W'] > 0

A     True
B     True
C    False
D     True
E     True
Name: W, dtype: bool

In [192]:
df[df['W']>0]

      W     X     Y     Z
A  2.71  0.63  0.91  0.50
B  0.65 -0.32 -0.85  0.61
D  0.19 -0.76 -0.93  0.96
E  0.19  1.98  2.61  0.68

In [193]:
df[df['W']>0]['Y'] # Retrieving specific column

A    0.91
B   -0.85
D   -0.93
E    2.61
Name: Y, dtype: float64

In [194]:
df[df['W']>0]['Y'].loc['A'] # Retrieving specific column and row

np.float64(0.91)

In [195]:
cond1 = df['W'] > 0
cond2 = df['Y'] > 1

df[cond1 & cond2]

      W     X     Y     Z
E  0.19  1.98  2.61  0.68

In [196]:
df[cond1 & cond2][['W','Y']]

      W     Y
E  0.19  2.61

In [197]:
df[cond1 & cond2][['X','Y']]

      X     Y
E  1.98  2.61

In [198]:
df.reset_index()

  index     W     X     Y     Z
0     A  2.71  0.63  0.91  0.50
1     B  0.65 -0.32 -0.85  0.61
2     C -2.02  0.74  0.53 -0.59
3     D  0.19 -0.76 -0.93  0.96
4     E  0.19  1.98  2.61  0.68

In [199]:
df['states'] = 'CA NY WY OR CO'.split()
df

      W     X     Y     Z states
A  2.71  0.63  0.91  0.50     CA
B  0.65 -0.32 -0.85  0.61     NY
C -2.02  0.74  0.53 -0.59     WY
D  0.19 -0.76 -0.93  0.96     OR
E  0.19  1.98  2.61  0.68     CO

In [200]:
df = df.set_index('states')

In [201]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, CA to CO
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   W       5 non-null      float64
 1   X       5 non-null      float64
 2   Y       5 non-null      float64
 3   Z       5 non-null      float64
dtypes: float64(4)
memory usage: 200.0+ bytes

In [202]:
df.describe().round(2)

          W     X     Y     Z
count  5.00  5.00  5.00  5.00
mean   0.34  0.45  0.45  0.43
std    1.68  1.06  1.46  0.60
min   -2.02 -0.76 -0.93 -0.59
25%    0.19 -0.32 -0.85  0.50
50%    0.19  0.63  0.53  0.61
75%    0.65  0.74  0.91  0.68
max    2.71  1.98  2.61  0.96

In [203]:
(df['W'] > 0).value_counts()

W
True     4
False    1
Name: count, dtype: int64

In [204]:
sum(df['W'] > 0)

4

In [205]:
len(df['W'] > 0)

5

----

In [206]:
df = pd.DataFrame({'A':[1,2,np.nan], 'B':[5,np.nan,np.nan], 'C':[1,2,3]})

In [207]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [208]:
df.dropna() # axis=0 is default and removes rows that contain NaN values

     A    B  C
0  1.0  5.0  1

In [209]:
df.dropna(axis=1) # removes columns that contain NaN values

   C
0  1
1  2
2  3

In [210]:
df.dropna(thresh=2) # thresh=int → require a minimum number of non-NA values

# You cannot use thresh and how together—they are mutually exclusive.
# If the number of non-NA values is less than thresh, the row/column is dropped.

# If you have thresh=2 and 3 columns, then:
	# Drop a row if it has 2 or more missing values (NaN).
	# Keep a row if it has fewer than 2 missing values.

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [211]:
df.fillna(value=0)

     A    B  C
0  1.0  5.0  1
1  2.0  0.0  2
2  0.0  0.0  3

In [212]:
df.fillna(df.mean())

     A    B  C
0  1.0  5.0  1
1  2.0  5.0  2
2  1.5  5.0  3

In [213]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

---

In [214]:
data = {
    'company':['GOOG', 'GOOG', 'MSFT', 'MSFT', 'FB', 'FB'],
    'person':['Sam', 'Charlie', 'Amy', 'Vanessa', 'Carl', 'Sarah'],
    'sales':[200,120,130,124,243,350]
}

df = pd.DataFrame(data)

In [215]:
df

  company   person  sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    130
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [216]:
!pip install pandas --upgrade

Requirement already satisfied: pandas in c:\users\loydt\appdata\local\programs\python\python313\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\loydt\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\loydt\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\loydt\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\loydt\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\loydt\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [217]:
df.groupby('company').mean(numeric_only=True) # In pandas 2.x, groupby().mean() fails on non-numeric columns; use numeric_only=True or select numeric columns.

         sales
company
FB       296.5
GOOG     160.0
MSFT     127.0

In [218]:
df.groupby('company')['sales'].max()

company
FB      350
GOOG    200
MSFT    130
Name: sales, dtype: int64

In [219]:
df.groupby('company').std(numeric_only=True).round(2)

         sales
company
FB       75.66
GOOG     56.57
MSFT      4.24

In [220]:
df.groupby('company').describe().round(2).transpose()

company          FB    GOOG    MSFT
sales count    2.00    2.00    2.00
      mean   296.50  160.00  127.00
      std     75.66   56.57    4.24
      min    243.00  120.00  124.00
      25%    269.75  140.00  125.50
      50%    296.50  160.00  127.00
      75%    323.25  180.00  128.50
      max    350.00  200.00  130.00

In [253]:
df.groupby('Bank Name').sum()['Fund  Sort ascending']

Bank Name
Almena State Bank                                        10538
Citizens Bank                                            10545
City National Bank of New Jersey                         10534
Ericson State Bank                                       10535
Fayette County Bank                                      10528
First City Bank of Florida                               10537
First NBC Bank                                           10526
First Republic Bank                                      10543
Guaranty Bank, (d/b/a BestBank in Georgia & Michigan)    10527
Harvest Community Bank                                   10523
Heartland Tri-State Bank                                 10544
Louisa Community Bank                                    10532
Proficio Bank                                            10525
Pulaski Savings Bank                                     10548
Republic First Bank dba Republic Bank                    10546
Resolute Bank                                            10533
Seaway Bank and Trust Company                            10524
Signature Bank                                           10540
Silicon Valley Bank                                      10539
The Enloe State Bank                                     10531
The Farmers and Merchants State Bank of Argonia          10529
The First National Bank of Lindsay                       10547
The First State Bank                                     10536
The Santa Anna National Bank                             10549
Washington Federal Bank for Savings                      10530
Name: Fund  Sort ascending, dtype: int64

---

In [221]:
np.arange(400,500,25)

array([400, 425, 450, 475])

In [222]:
df = pd.DataFrame({
    'col1':[1,2,3,4],
    'col2':np.arange(400,500,25),
    'col3':['ab', 'cd', 'ef', 'gh']
})

In [223]:
def times_two(num: float):
    return num * 2

In [224]:
df.apply(times_two)

   col1  col2  col3
0     2   800  abab
1     4   850  cdcd
2     6   900  efef
3     8   950  ghgh

In [225]:
df['new'] = df['col1'].apply(times_two)

In [226]:
df

   col1  col2 col3  new
0     1   400   ab    2
1     2   425   cd    4
2     3   450   ef    6
3     4   475   gh    8

In [227]:
del df['new']

In [228]:
df

   col1  col2 col3
0     1   400   ab
1     2   425   cd
2     3   450   ef
3     4   475   gh

In [229]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [230]:
df.describe().round(2)

       col1    col2
count  4.00    4.00
mean   2.50  437.50
std    1.29   32.27
min    1.00  400.00
25%    1.75  418.75
50%    2.50  437.50
75%    3.25  456.25
max    4.00  475.00

In [231]:
df.sort_values(by='col2', ascending=False)

   col1  col2 col3
3     4   475   gh
2     3   450   ef
1     2   425   cd
0     1   400   ab

---

| Format Type | Data Description | Reader | Writer |
| :--- | :--- | :--- | :--- |
| text | CSV | `read_csv` | `to_csv` |
| text | Fixed-Width Text File | `read_fwf` | NA |
| text | JSON | `read_json` | `to_json` |
| text | HTML | `read_html` | `to_html` |
| text | LaTeX | `Styler.to_latex` | NA |
| text | XML | `read_xml` | `to_xml` |
| text | Local clipboard | `read_clipboard` | `to_clipboard` |
| binary | MS Excel | `read_excel` | `to_excel` |
| binary | OpenDocument | `read_excel` | NA |
| binary | HDF5 Format | `read_hdf` | `to_hdf` |
| binary | Feather Format | `read_feather` | `to_feather` |
| binary | Parquet Format | `read_parquet` | `to_parquet` |
| binary | ORC Format | `read_orc` | `to_orc` |
| binary | Stata | `read_stata` | `to_stata` |
| binary | SAS | `read_sas` | NA |
| binary | SPSS | `read_spss` | NA |
| binary | Python Pickle Format | `read_pickle` | `to_pickle` |
| SQL | SQL | `read_sql` | `to_sql` |
| SQL | Google BigQuery | `read_gbq` | `to_gbq` |

In [247]:
!pip install lxml
df = pd.read_html('http://www.fdic.gov/bank/individual/failed/banklist.html')

Requirement already satisfied: lxml in c:\users\loydt\appdata\local\programs\python\python313\lib\site-packages (6.0.2)

In [248]:
df = df[0]

In [249]:
df.columns = df.columns.str.strip()

In [250]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Bank Name              25 non-null     object
 1   City                   25 non-null     object
 2   State                  25 non-null     object
 3   Cert                   25 non-null     int64
 4   Acquiring Institution  25 non-null     object
 5   Closing Date           25 non-null     object
 6   Fund  Sort ascending   25 non-null     int64
dtypes: int64(2), object(5)
memory usage: 1.5+ KB

In [256]:
df.groupby('Bank Name')['Fund  Sort ascending'].sum()

Bank Name
Almena State Bank                                        10538
Citizens Bank                                            10545
City National Bank of New Jersey                         10534
Ericson State Bank                                       10535
Fayette County Bank                                      10528
First City Bank of Florida                               10537
First NBC Bank                                           10526
First Republic Bank                                      10543
Guaranty Bank, (d/b/a BestBank in Georgia & Michigan)    10527
Harvest Community Bank                                   10523
Heartland Tri-State Bank                                 10544
Louisa Community Bank                                    10532
Proficio Bank                                            10525
Pulaski Savings Bank                                     10548
Republic First Bank dba Republic Bank                    10546
Resolute Bank                                            10533
Seaway Bank and Trust Company                            10524
Signature Bank                                           10540
Silicon Valley Bank                                      10539
The Enloe State Bank                                     10531
The Farmers and Merchants State Bank of Argonia          10529
The First National Bank of Lindsay                       10547
The First State Bank                                     10536
The Santa Anna National Bank                             10549
Washington Federal Bank for Savings                      10530
Name: Fund  Sort ascending, dtype: int64

In [255]:
df.groupby('Bank Name').sum().sort_values('Fund  Sort ascending', ascending=False).head()

,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
Bank Name,,,,,,
The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545