In [ ]:
import pandas as pd

df = pd.read_csv("D:/E-commerce/Project/traffic_data.csv", dtype=str) # --> created the dataset using faker module

In [23]:
df.head()

   user_id          customer session_start_time session_end_time
0  MH72520      Marie Martin           07:38:AM         07:13:PM
1  PA06552  Alexandra Palmer           12:51:PM         07:07:PM
2  WV46033      Brett Gaines           01:20:PM         07:09:PM
3  ID80288       Laura Parks           06:43:PM         04:59:AM
4  TX23022       Joseph Chen           09:02:AM         09:00:AM

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 529885 entries, 0 to 529884
Data columns (total 4 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   user_id             500000 non-null  object
 1   customer            500000 non-null  object
 2   session_start_time  500000 non-null  object
 3   session_end_time    500000 non-null  object
dtypes: object(4)
memory usage: 16.2+ MB

In [25]:
urls = [
    "https://williams.org/",
    "http://www.ramirez-vazquez.com/",
    "http://www.stone-shaffer.net/",
    "https://www.gutierrez.com/",
    "https://www.wilson.com/",
    "https://ford.info/",
    "https://stokes.com/",
    "https://gonzalez.com/",
    "https://huang.com/",
    "http://lewis.com/"
]

In [ ]:
import numpy as np

df['visited_website'] = np.random.choice(urls, size=len(df))

In [27]:
df.head()

,user_id,customer,session_start_time,session_end_time,visited_website
0,MH72520,Marie Martin,07:38:AM,07:13:PM,https://www.gutierrez.com/
1,PA06552,Alexandra Palmer,12:51:PM,07:07:PM,http://www.ramirez-vazquez.com/
2,WV46033,Brett Gaines,01:20:PM,07:09:PM,https://www.gutierrez.com/
3,ID80288,Laura Parks,06:43:PM,04:59:AM,https://williams.org/
4,TX23022,Joseph Chen,09:02:AM,09:00:AM,https://www.wilson.com/

In [ ]:
# Date manipulation
import datetime

x = datetime.datetime.now()

print(x)

2025-12-16 05:43:57.590931

In [2]:
print(x.year)

2025

In [3]:
print(x.strftime("%A"))

Tuesday

In [ ]:
from datetime import timedelta

delta = timedelta(
    days=30,
    seconds=60,
    microseconds=20,
    milliseconds=30000,
    minutes=15,
    hours=10,
    weeks=3 
)

delta

datetime.timedelta(days=51, seconds=36990, microseconds=20)